name: canvas_kit
description: "Composable infinite pan/zoom canvas for Flutter with interactive and programmatic camera control."
version: 0.5.2
homepage: https://github.com/vento007/canvas_kit
repository: https://github.com/vento007/canvas_kit
issue_tracker: https://github.com/vento007/canvas_kit/issues

topics:
  - flutter
  - canvas
  - pan-and-zoom
  - infinite-canvas
  - graphics

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:

 